tiles.setCurrentTilemap(tilemap`level2`)
let Mandy = sprites.create(assets.image`Mandy`, SpriteKind.Player)
scaling.scaleToPixels(Mandy, 34, ScaleDirection.Uniformly, ScaleAnchor.Middle)
tiles.placeOnTile(Mandy, tiles.getTileLocation(1, 1))
mp.setPlayerSprite(mp.playerSelector(mp.PlayerNumber.One), Mandy)
let Piper = sprites.create(assets.image`Piper`, SpriteKind.Player)
scaling.scaleToPixels(Piper, 33, ScaleDirection.Uniformly, ScaleAnchor.Middle)
tiles.placeOnTile(Piper, tiles.getTileLocation(8, 1))
mp.setPlayerSprite(mp.playerSelector(mp.PlayerNumber.Two), Piper)
let Fang = sprites.create(assets.image`Fang`, SpriteKind.Player)
scaling.scaleToPixels(Fang, 34, ScaleDirection.Uniformly, ScaleAnchor.Middle)
tiles.placeOnTile(Fang, tiles.getTileLocation(1, 5))
mp.setPlayerSprite(mp.playerSelector(mp.PlayerNumber.Three), Fang)
let Brock = sprites.create(assets.image`Brock`, SpriteKind.Player)
scaling.scaleToPixels(Brock, 66, ScaleDirection.Horizontally, ScaleAnchor.Middle)
scaling.scaleToPixels(Brock, 32, ScaleDirection.Vertically, ScaleAnchor.Middle)
tiles.placeOnTile(Brock, tiles.getTileLocation(8, 5))
mp.setPlayerSprite(mp.playerSelector(mp.PlayerNumber.Four), Brock)
